ost_utils: fix encoding on binary open()
Fix the following error:
ValueError: binary mode doesn't take an encoding argument

This was added by mistake in a73a923cb266d4b0c3f1fb981e0e333da7b277a0.

Signed-off-by: Jean-Louis Dupond <jean-louis@dupond.be>