ost_utils: Add assert_utils for more readable asserts
The old assert_equals_within functions have unfortunate effect of
messing up the traceback with it's own code, which isn't important
for decrypting the cause of the error.

The new equals_within functions are instead to be used with normal
assert statement and therefore the traceback will end on the
assertion line. With pytest's formatting this will lead to more
readable output like:

```
    def test_traceback():
>       assert equals_within_short(return_false, True)
E       assert return_false() -> False != True after 180 seconds
E        +  where return_false() -> False != True after 180 seconds = equals_within_short(return_false, True)
```

Change-Id: I398e58ee88dd2b3ea21985dd35b60ed25f4d6b5c
Signed-off-by: Andrej Cernek <acernek@redhat.com>