give snapshot removal error some meaning
while debugging hc-basic-suite-master I was looking at test result
https://jenkins.ovirt.org/job/ovirt-system-tests_hc-basic-suite-master/lastCompletedBuild/testReport/(root)/004_basic_sanity/snapshot_merge/
Error message there was:

Error Message
False != True after 180 seconds

Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 142, in wrapped_test
    test()
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 60, in wrapper
    return func(get_test_prefix(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 69, in wrapper
    return func(prefix.virt_env.engine_vm().get_api(), *args, **kwargs)
  File "/home/jenkins/workspace/ovirt-system-tests_hc-basic-suite-master/ovirt-system-tests/hc-basic-suite-master/test-scenarios/004_basic_sanity.py", line 203, in snapshot_merge
    lambda:
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 282, in assert_true_within_short
    assert_equals_within_short(func, True, allowed_exceptions)
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 266, in assert_equals_within_short
    func, value, SHORT_TIMEOUT, allowed_exceptions=allowed_exceptions
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 252, in assert_equals_within
    '%s != %s after %s seconds' % (res, value, timeout)
AssertionError: False != True after 180 seconds

The error message there was completely not useful since False != True
always. Added new parameter error_message to:
- assert_true_within_short
- assert_equals_within_short
- assert_equals_within

allowing to raise more meaningful error messages for helping with
debugs.

Added an error message to the snapshot_merge test in basic_sanity module
to verify this patch if the original issue still reproduce.
In order to test the ost_utils testlib changes, switched contextually
from ovirtlago.testlib to ost_utils.testlib

Change-Id: I2be196e106a5083312e58039db63aaab7219d2ec
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>